import type { Course, Student, StudentProgress, EngagementData, Quiz, QuizAttempt } from './types';

export const students: Student[] = [
  { id: 'student-1', name: 'Alex Johnson', avatarUrl: 'https://i.pravatar.cc/150?u=student-1' },
  { id: 'student-2', name: 'Maria Garcia', avatarUrl: 'https://i.pravatar.cc/150?u=student-2' },
  { id: 'student-3', name: 'James Smith', avatarUrl: 'https://i.pravatar.cc/150?u=student-3' },
];

export const courses: Course[] = [
  {
    id: 'cs101',
    title: 'Introduction to Python',
    description: 'Learn the fundamentals of Python programming. No prior experience needed.',
    imageId: 'course-1',
    materials: [
      { id: 'mat-1', title: 'Week 1: Introduction', type: 'PDF', content: 'This is the content for the week 1 PDF. It covers basic syntax, variables, and data types in Python. We will learn how to write our first "Hello, World!" program.' },
      { id: 'mat-2', title: 'Week 2: Control Flow', type: 'PPT', content: 'This presentation covers control flow using if-else statements and loops (for and while). Includes examples and exercises on conditional logic.' },
    ],
    learningObjectives: '1. Understand basic Python syntax. 2. Use variables and data types. 3. Implement control flow structures.',
    learningSkills: 'Problem-solving, Algorithmic thinking',
    learningTrajectories: 'Beginner -> Intermediate',
  },
  {
    id: 'cs202',
    title: 'Data Structures & Algorithms',
    description: 'A deep dive into common data structures and algorithms.',
    imageId: 'course-6',
    materials: [
      { id: 'mat-3', title: 'Module 1: Arrays & Strings', type: 'MD', content: 'Markdown content for Arrays and Strings. Covers operations, complexity analysis, and common problems.' },
      { id: 'mat-4', title: 'Module 2: Linked Lists', type: 'DOC', content: 'A document about singly and doubly linked lists. Includes implementation details and traversal techniques.' },
    ],
    learningObjectives: '1. Implement various data structures. 2. Analyze algorithm complexity. 3. Solve problems using appropriate data structures.',
    learningSkills: 'Analytical skills, Efficiency analysis',
    learningTrajectories: 'Intermediate -> Advanced',
  },
  {
    id: 'cs303',
    title: 'Machine Learning Foundations',
    description: 'Explore the core concepts of machine learning and neural networks.',
    imageId: 'course-4',
    materials: [
        { id: 'mat-5', title: 'Concept: Supervised Learning', type: 'PDF', content: 'A PDF explaining supervised learning, including regression and classification models.' },
        { id: 'mat-6', title: 'Concept: Neural Networks', type: 'PPT', content: 'Presentation on the basics of neural networks, neurons, and activation functions.' },
    ],
    learningObjectives: '1. Understand ML concepts. 2. Build simple ML models. 3. Differentiate between supervised and unsupervised learning.',
    learningSkills: 'Statistical analysis, Model building',
    learningTrajectories: 'Intermediate -> Advanced',
  },
];

export const studentProgress: StudentProgress[] = [
    { studentId: 'student-1', courseId: 'cs101', progress: 75, questionsAsked: 12, lastAccessed: '2024-05-20T10:00:00Z' },
    { studentId: 'student-2', courseId: 'cs101', progress: 45, questionsAsked: 5, lastAccessed: '2024-05-19T14:30:00Z' },
    { studentId: 'student-3', courseId: 'cs101', progress: 90, questionsAsked: 25, lastAccessed: '2024-05-21T09:00:00Z' },
    { studentId: 'student-1', courseId: 'cs202', progress: 30, questionsAsked: 8, lastAccessed: '2024-05-18T11:00:00Z' },
];

export const engagementData: EngagementData[] = [
    { date: 'May 1', logins: 150, questions: 45 },
    { date: 'May 2', logins: 160, questions: 50 },
    { date: 'May 3', logins: 155, questions: 48 },
    { date: 'May 4', logins: 170, questions: 60 },
    { date: 'May 5', logins: 180, questions: 65 },
    { date: 'May 6', logins: 175, questions: 58 },
    { date: 'May 7', logins: 190, questions: 70 },
];

export const getCourseById = (id: string) => courses.find(c => c.id === id);

// Quiz Mock Data
export const quizzes: Quiz[] = [
  {
    id: 'quiz-1',
    courseId: 'cs101',
    title: 'Python Basics Quiz',
    description: 'Test your knowledge of Python fundamentals including syntax, variables, and basic data types.',
    createdBy: 'teacher-1',
    createdAt: '2024-05-15T10:00:00Z',
    totalPoints: 10,
    difficulty: 'easy',
    topics: ['Python Syntax', 'Variables', 'Data Types'],
    questions: [
      {
        id: 'q1',
        questionText: 'What is the correct way to print "Hello, World!" in Python?',
        questionType: 'multiple-choice',
        options: [
          'print("Hello, World!")',
          'echo "Hello, World!"',
          'console.log("Hello, World!")',
          'printf("Hello, World!")',
        ],
        correctAnswer: 'print("Hello, World!")',
        explanation: 'In Python, the print() function is used to output text to the console. This is covered in Week 1 materials where we introduced basic Python syntax.',
        points: 2,
        topic: 'Python Syntax',
      },
      {
        id: 'q2',
        questionText: 'In Python, variables must be declared with a specific type before use.',
        questionType: 'true-false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Python is a dynamically typed language, which means you do not need to declare variable types. The type is inferred at runtime based on the value assigned.',
        points: 2,
        topic: 'Variables',
      },
      {
        id: 'q3',
        questionText: 'Which of the following is NOT a valid Python data type?',
        questionType: 'multiple-choice',
        options: ['int', 'float', 'string', 'char'],
        correctAnswer: 'char',
        explanation: 'Python does not have a char data type. Individual characters are represented as strings of length 1. The basic data types in Python are int, float, str, bool, list, tuple, dict, and set.',
        points: 3,
        topic: 'Data Types',
      },
      {
        id: 'q4',
        questionText: 'What keyword is used to define a function in Python?',
        questionType: 'short-answer',
        correctAnswer: 'def',
        explanation: 'The "def" keyword is used to define functions in Python, followed by the function name and parameters in parentheses.',
        points: 3,
        topic: 'Python Syntax',
      },
    ],
  },
  {
    id: 'quiz-2',
    courseId: 'cs101',
    title: 'Control Flow Mastery',
    description: 'Challenge yourself with questions about if-else statements, loops, and conditional logic.',
    createdBy: 'teacher-1',
    createdAt: '2024-05-18T14:00:00Z',
    totalPoints: 15,
    difficulty: 'medium',
    topics: ['Conditionals', 'Loops', 'Control Flow'],
    questions: [
      {
        id: 'q5',
        questionText: 'What will be the output of the following code?\n\nfor i in range(3):\n    print(i)',
        questionType: 'multiple-choice',
        options: ['0 1 2', '1 2 3', '0 1 2 3', 'Error'],
        correctAnswer: '0 1 2',
        explanation: 'The range(3) function generates numbers from 0 to 2 (not including 3). The loop will iterate three times, printing 0, 1, and 2.',
        points: 3,
        topic: 'Loops',
      },
      {
        id: 'q6',
        questionText: 'A while loop continues executing as long as its condition is True.',
        questionType: 'true-false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'A while loop evaluates its condition before each iteration. If the condition is True, the loop body executes. When the condition becomes False, the loop terminates.',
        points: 2,
        topic: 'Loops',
      },
      {
        id: 'q7',
        questionText: 'Which statement is used to exit a loop prematurely in Python?',
        questionType: 'multiple-choice',
        options: ['exit', 'break', 'stop', 'end'],
        correctAnswer: 'break',
        explanation: 'The "break" statement immediately exits the current loop, regardless of the loop condition. This is useful when you want to stop iteration based on a specific condition.',
        points: 4,
        topic: 'Control Flow',
      },
      {
        id: 'q8',
        questionText: 'What does the "elif" keyword stand for in Python?',
        questionType: 'short-answer',
        correctAnswer: 'else if',
        explanation: '"elif" is short for "else if" and is used to check multiple conditions in sequence. If the first condition is False, it checks the elif condition.',
        points: 3,
        topic: 'Conditionals',
      },
      {
        id: 'q9',
        questionText: 'What is the purpose of the "continue" statement in a loop?',
        questionType: 'short-answer',
        correctAnswer: 'skip the rest of the current iteration',
        explanation: 'The "continue" statement skips the remaining code in the current iteration and moves to the next iteration of the loop.',
        points: 3,
        topic: 'Control Flow',
      },
    ],
  },
  {
    id: 'quiz-3',
    courseId: 'cs202',
    title: 'Arrays and Complexity Analysis',
    description: 'Test your understanding of array operations and Big-O notation.',
    createdBy: 'teacher-1',
    createdAt: '2024-05-20T09:00:00Z',
    totalPoints: 18,
    difficulty: 'hard',
    topics: ['Arrays', 'Time Complexity', 'Space Complexity'],
    questions: [
      {
        id: 'q10',
        questionText: 'What is the time complexity of accessing an element by index in an array?',
        questionType: 'multiple-choice',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
        correctAnswer: 'O(1)',
        explanation: 'Array access by index is a constant time operation O(1) because the memory address can be calculated directly using the base address and index.',
        points: 3,
        topic: 'Time Complexity',
      },
      {
        id: 'q11',
        questionText: 'Searching for an element in an unsorted array requires checking all elements in the worst case.',
        questionType: 'true-false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'In an unsorted array, you must perform a linear search which checks each element until the target is found or all elements are checked, resulting in O(n) time complexity.',
        points: 3,
        topic: 'Arrays',
      },
      {
        id: 'q12',
        questionText: 'What is the time complexity of inserting an element at the beginning of an array?',
        questionType: 'multiple-choice',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
        correctAnswer: 'O(n)',
        explanation: 'Inserting at the beginning requires shifting all existing elements one position to the right, which takes O(n) time where n is the number of elements.',
        points: 4,
        topic: 'Time Complexity',
      },
      {
        id: 'q13',
        questionText: 'What data structure would you use for dynamic resizing with O(1) amortized append operations?',
        questionType: 'short-answer',
        correctAnswer: 'dynamic array',
        explanation: 'A dynamic array (or ArrayList) provides O(1) amortized time for append operations by doubling its capacity when full, spreading the cost of resizing over many operations.',
        points: 4,
        topic: 'Arrays',
      },
      {
        id: 'q14',
        questionText: 'Explain the difference between O(n) and O(n^2) time complexity in terms of how running time grows with input size.',
        questionType: 'short-answer',
        correctAnswer: 'O(n) grows linearly while O(n^2) grows quadratically',
        explanation: 'O(n) means the running time increases linearly with input size (e.g., single loop), while O(n^2) means it increases quadratically (e.g., nested loops), making O(n^2) much slower for large inputs.',
        points: 4,
        topic: 'Time Complexity',
      },
    ],
  },
];

export const quizAttempts: QuizAttempt[] = [
  {
    id: 'attempt-1',
    quizId: 'quiz-1',
    studentId: 'student-1',
    courseId: 'cs101',
    startedAt: '2024-05-21T10:00:00Z',
    completedAt: '2024-05-21T10:15:00Z',
    status: 'completed',
    score: 8,
    maxScore: 10,
    answers: [
      {
        questionId: 'q1',
        studentAnswer: 'print("Hello, World!")',
        isCorrect: true,
        pointsEarned: 2,
      },
      {
        questionId: 'q2',
        studentAnswer: 'False',
        isCorrect: true,
        pointsEarned: 2,
      },
      {
        questionId: 'q3',
        studentAnswer: 'string',
        isCorrect: false,
        pointsEarned: 0,
      },
      {
        questionId: 'q4',
        studentAnswer: 'def',
        isCorrect: true,
        pointsEarned: 3,
      },
    ],
  },
  {
    id: 'attempt-2',
    quizId: 'quiz-1',
    studentId: 'student-2',
    courseId: 'cs101',
    startedAt: '2024-05-21T11:00:00Z',
    completedAt: null,
    status: 'in-progress',
    score: 0,
    maxScore: 10,
    answers: [
      {
        questionId: 'q1',
        studentAnswer: 'print("Hello, World!")',
        isCorrect: true,
        pointsEarned: 2,
      },
      {
        questionId: 'q2',
        studentAnswer: 'True',
        isCorrect: false,
        pointsEarned: 0,
      },
    ],
  },
  {
    id: 'attempt-3',
    quizId: 'quiz-2',
    studentId: 'student-3',
    courseId: 'cs101',
    startedAt: '2024-05-22T09:00:00Z',
    completedAt: '2024-05-22T09:25:00Z',
    status: 'completed',
    score: 13,
    maxScore: 15,
    answers: [
      {
        questionId: 'q5',
        studentAnswer: '0 1 2',
        isCorrect: true,
        pointsEarned: 3,
      },
      {
        questionId: 'q6',
        studentAnswer: 'True',
        isCorrect: true,
        pointsEarned: 2,
      },
      {
        questionId: 'q7',
        studentAnswer: 'break',
        isCorrect: true,
        pointsEarned: 4,
      },
      {
        questionId: 'q8',
        studentAnswer: 'else if',
        isCorrect: true,
        pointsEarned: 3,
      },
      {
        questionId: 'q9',
        studentAnswer: 'skip',
        isCorrect: false,
        pointsEarned: 0,
      },
    ],
  },
];

export const getQuizById = (id: string) => quizzes.find(q => q.id === id);
export const getQuizzesByCourseId = (courseId: string) => quizzes.filter(q => q.courseId === courseId);
export const getQuizAttemptsByStudentId = (studentId: string) => quizAttempts.filter(a => a.studentId === studentId);
export const getQuizAttemptsByQuizId = (quizId: string) => quizAttempts.filter(a => a.quizId === quizId);
