/**
 * Test data seeding utility
 * Seeds quiz data from mock-data.ts into Firestore emulator via API routes
 */

import { quizzes } from '../../src/lib/mock-data';
import type { Quiz } from '../../src/lib/types';

const BASE_URL = process.env.BASE_URL || 'http://localhost:9002';

/**
 * Seed quizzes into Firestore emulator via API
 */
export async function seedQuizzes(baseURL: string = BASE_URL): Promise<void> {
  console.log('[Seed Data] Starting quiz data seeding...');
  
  const seededQuizzes: string[] = [];
  const errors: string[] = [];

  for (const quiz of quizzes) {
    try {
      // Remove id and createdAt - these are generated by the API
      const { id, createdAt, ...quizData } = quiz;
      
      // Use teacher-1 as createdBy to match the page's CURRENT_TEACHER_ID constant
      const quizToCreate = {
        ...quizData,
        createdBy: 'teacher-1',
      };

      const response = await fetch(`${baseURL}/api/quizzes`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(quizToCreate),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ error: response.statusText }));
        throw new Error(errorData.message || errorData.error || `HTTP ${response.status}`);
      }

      const createdQuiz = await response.json();
      seededQuizzes.push(createdQuiz.id || quiz.id);
      console.log(`[Seed Data] ✓ Seeded quiz: "${quiz.title}" (ID: ${createdQuiz.id || quiz.id})`);
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      errors.push(`${quiz.title}: ${errorMsg}`);
      console.error(`[Seed Data] ✗ Failed to seed quiz "${quiz.title}":`, errorMsg);
    }
  }

  console.log(`[Seed Data] Seeding complete. ${seededQuizzes.length}/${quizzes.length} quizzes seeded.`);
  
  if (errors.length > 0) {
    console.warn('[Seed Data] Errors encountered:');
    errors.forEach(err => console.warn(`  - ${err}`));
  }

  if (seededQuizzes.length === 0) {
    throw new Error('Failed to seed any quizzes. Check API connectivity and emulator status.');
  }
}

/**
 * Clear all quizzes from Firestore emulator
 * Note: This is optional and may not be needed if tests clean up after themselves
 */
export async function clearQuizzes(baseURL: string = BASE_URL): Promise<void> {
  console.log('[Seed Data] Clearing quiz data...');
  
  try {
    // Get all quizzes
    const response = await fetch(`${baseURL}/api/quizzes`);
    if (!response.ok) {
      console.warn('[Seed Data] Could not fetch quizzes for cleanup');
      return;
    }

    const quizzes: Quiz[] = await response.json();
    
    // Delete each quiz
    for (const quiz of quizzes) {
      try {
        await fetch(`${baseURL}/api/quizzes/${quiz.id}`, {
          method: 'DELETE',
        });
        console.log(`[Seed Data] Deleted quiz: ${quiz.id}`);
      } catch (error) {
        console.warn(`[Seed Data] Failed to delete quiz ${quiz.id}:`, error);
      }
    }

    console.log(`[Seed Data] Cleared ${quizzes.length} quizzes`);
  } catch (error) {
    console.warn('[Seed Data] Error during cleanup:', error);
  }
}
